spring:
  #  DataBase
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  #  Cache
  cache:
    type: none
  #  Redis
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  #    Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  #    Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    #      properties:
    #        spring.json.trusted.packages: "*"
    #        spring.json.value.default.type: FirstRestApp.dto.MeasurementDto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    #       spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual_immediate

  config:
    import: file:secret.yml
#    Logging
logging:
  level:
    root: info
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.data.redis.core.RedisTemplate: DEBUG
    org.springframework.data.redis.cache: DEBUG
#    Actuator
management:
  endpoints:
    web:
      exposure:
        include: caches
# RSA Public & Private Keys
jwt:
  rsa:
    public-key: classpath:keys/public.pem
    private-key: classpath:keys/private.pem





